# Generated by Django 4.0.2 on 2022-08-31 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_post_videofile_post_embed_alter_post_opis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/homepage/')),
                ('opis', models.CharField(blank=True, max_length=3096)),
            ],
        ),
        migrations.DeleteModel(
            name='URL',
        ),
        migrations.AlterField(
            model_name='post',
            name='embed',
            field=models.URLField(default='www.anylogic.com', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^(https?:\\/\\/)?(www.)?cloud(\\.)anylogic(\\.)com(\\/)assets(\\/)embed(\\?)modelId=([a-zA-Z0-9]){8}-([a-zA-Z0-9]){4}-([a-zA-Z0-9]){4}-([a-zA-Z0-9]){4}-([a-zA-Z0-9]){12}$', code='Invalid name', message='Please insert a correct URL')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='opis',
            field=models.CharField(blank=True, max_length=3096),
        ),
    ]
